debug: true
branches: 
- '+([0-9])?(.{+([0-9]),x}).x'
- 'main'
- 'next'
- 'next-major'
- {name: 'beta', prerelease: true}
- {name: 'alpha', prerelease: true}
plugins:
- - "@semantic-release/commit-analyzer"
  - preset: angular
    parserOpts:
      noteKeywords:
        - BREAKING CHANGE
        - BREAKING CHANGES
        - BREAKING
- - "@semantic-release/release-notes-generator"
  - preset: angular
    parserOpts:
      noteKeywords:
        - BREAKING CHANGE
        - BREAKING CHANGES
        - BREAKING
    writerOpts:
      commitsSort:
        - subject
        - scope
- - "@semantic-release/exec"
  - prepareCmd: "dotnet pack -c Release -o ./artifacts /p:Version=${nextRelease.version}"  
    publishCmd: "dotnet nuget push ./artifacts/*.nupkg --skip-duplicate -s github"
- - "@semantic-release/github"
  - successComment: false
    failComment: false
    assets: 
    - path: "artifacts/*.nupkg"
