version: "3.7"

volumes:
  gitea:
    driver: local
  
  db:
    driver: local
  
  dex:
    driver: local

services:
  redis:
    image: redis:5.0.5-alpine
    ports:
      - 6370:6379
  
  postgres:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/

  nats:
    image: nats:latest
    command:
      - -js
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
