name: Build and Test Branches

on:
  push:
    branches:
      - feature/*
      - bugfix/*

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Debug Action Contexts
      uses: henrygriffiths/debug_action@v1
      with:
        secrets_context: ${{ toJson(secrets) }}
        needs_context: ${{ toJson(needs) }}
  
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
        
    - name: Build and Package
      run: |
        VERSION="${{ steps.version.outputs.value }}"
        OMNICAVE_NUGET_PASSWORD="${{ secrets.GITHUB_TOKEN }}"
        # dotnet nuget add source --username gh-actions --password  --store-password-in-clear-text --name github "https://nuget.pkg.github.com/omnicave/index.json"
        dotnet build -c Release