name: Build and Test Main Line

on:
  push:
    branches:
      - main
      - alpha

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Debug Action Contexts
      uses: henrygriffiths/debug_action@v1
      with:
        secrets_context: ${{ toJson(secrets) }}
        needs_context: ${{ toJson(needs) }}
  
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - run: npm ci
    - run: |
        dotnet nuget add source --username gh-actions \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text \
          --name github "https://nuget.pkg.github.com/omnicave/index.json"
    - run: ./node_modules/.bin/semantic-release
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#    - name: Build and Package
#      run: |
#        VERSION="${{ steps.version.outputs.value }}"
#        
#        dotnet nuget add source --username gh-actions --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/omnicave/index.json"
#        
#        dotnet build -c Release /p:Version="$VERSION"
#        dotnet pack -c Release --no-build /p:Version="$VERSION" -o ./packages