name: .NET Release

on:
  push:
    tags:
      - "*"

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Action Contexts
        uses: henrygriffiths/debug_action@v1
        with:
          secrets_context: ${{ toJson(secrets) }}
          needs_context: ${{ toJson(needs) }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Determine Version
        id: version
        run: |         
          echo "GITHUB_REF: ${GITHUB_REF}"
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "value=${VERSION}" >> $GITHUB_OUTPUT
          
      - name: Build and Package
        run: |
          VERSION="${{ steps.version.outputs.value }}"

          dotnet nuget add source --username gh-actions --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/omnicave/index.json"
          
          dotnet build -c Release /p:Version="$VERSION"
          dotnet pack -c Release --no-build /p:Version="$VERSION" -o ./packages          
          dotnet nuget push ./packages/*.nupkg --skip-duplicate -s github          
